#! /bin/bash

. ./config.cfg

## CONFIGURE FOR SLURM/PBS
# First check for scheduler, then copy appropriate files
if [[ "${SCHED^^}"  ==  "PBS" ]]; then
    echo "PBS Setup Specified"
    echo "Reconfiguring PPMAP for PBS"
    cp ./templates/template_premap_PBS.f90 ./src/premap.f90
    cp ./templates/template_run_ppmap_PBS.sh ./templates/template_run_ppmap.sh
    sed -i "s+\[JOBID\]+$JOBID+g" ./templates/template_run_ppmap.sh 
elif [[ "${SCHED^^}" == "SLURM" ]]; then
    echo "SLURM Setup Specified"
    echo "Reconfiguring PPMAP for SLURM"
    cp ./templates/template_premap_SLURM.f90 ./src/premap.f90
    cp ./templates/template_run_ppmap_SLURM.sh ./templates/template_run_ppmap.sh
else
   echo "Unknown cluster scheduler specified in config.cfg"
fi

## EDIT THE SHELL SCRIPT TEMPLATE
# First edit paths (need to do this before USERNAME gets altered)
cp ./templates/template_run_ppmap.sh ./run_ppmap.sh
sed -i "s+code=+code=$PPPATH+g" ./run_ppmap.sh
sed -i "s+MYPATH=+MYPATH=$OUTPATH+g" ./run_ppmap.sh

# Then edit USERNAME everywhere
sed -i "s+\[USERNAME\]+$USERNAME+g" ./run_ppmap.sh

# Finally edit load command for intel compiler
sed -i "s+module load +module load $COMPILER+g" ./run_ppmap.sh

## EDIT THE RUN_[FIELD]_ALL TEMPLATE
# First edit the username field
cp ./templates/template_run_[FIELD]_all ./run_[FIELD]_all
sed -i "s+\[BINPATH\]+$BINPATH+g" ./run_[FIELD]_all
sed -i "s+\[OUTPATH\]+$OUTPATH+g" ./run_[FIELD]_all

# Then edit USERNAME everywhere
sed -i "s+\[USERNAME\]+$USERNAME+g" ./run_[FIELD]_all

# Finally edit the compiler
sed -i "s+\[COMPILER\]+$COMPILER+g" ./run_[FIELD]_all
